spring.application.name=hospital-management-system

# Server port
server.port=8080

# SQLite Database configuration
spring.datasource.url=jdbc:sqlite:hmsdb.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate configuration
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
